import { FAQ_IDS } from "./constants.js";

export const faqCopy = {
  de: {
    "meta.title": "FAQ — Sprachen, Ablauf, Pakete | Peivando",
    "meta.desc": "Häufige Fragen zu Sprachen, RTL, Ablauf, Paketen, WhatsApp und Zeitrahmen. Ehrlich beantwortet — ohne Fake-Bewertungen.",
    "skip": "Zum Inhalt",
    "nav.about": "Über uns",
    "nav.faq": "FAQ",
    "langs.label": "Sprache",
    "eyebrow": "FAQ",
    "title": "Klare Antworten, ohne Verkaufstheater.",
    "lede": "Sprachen, RTL, Ablauf, Pakete, WhatsApp und Zeitrahmen. Wo wir etwas noch nicht öffentlich machen können — etwa eine deutsche Telefonnummer — sagen wir das.",
    "cta.talk": "Kostenloses Erstgespräch",
    "cta.about": "Über Peivando",
    "cta.wa": "Per WhatsApp schreiben",
    "cta.waText": "Hallo Peivando, ich habe eine Frage zur Website.",
    "faq.languages.q": "In welchen Sprachen arbeitet ihr?",
    "faq.languages.a": "Deutsch, Englisch, Dari (دری) und Farsi (فارسی). Beratung, Inhalte und die Website selbst können in diesen Sprachen laufen. Weitere Sprachen sind möglich; dann klären wir Übersetzung und Satz gesondert. Alle vier Sprachen sind auf der Website wählbar.",
    "faq.rtl.q": "Was ist RTL — und warum ist das wichtig?",
    "faq.rtl.a": "Dari und Farsi werden von rechts nach links gelesen. Das betrifft Navigation, Formulare, Abstände und Zahlen, nicht nur einen Textblock. Eine gespiegelte deutsche Seite ist kein RTL-Layout. Wir setzen die Leserichtung als Layout um.",
    "faq.process.q": "Wie läuft ein Projekt ab?",
    "faq.process.a": "<p>Vier Schritte, in dieser Reihenfolge:</p><ol><li><strong>Gespräch</strong> — Was Ihr Betrieb macht, wer Sie finden soll, was heute fehlt. Kostenlos, ohne Verpflichtung.</li><li><strong>Entwurf</strong> — Struktur und Design, bevor gebaut wird.</li><li><strong>Umsetzung</strong> — Bau, Test auf Handy, Tablet und Desktop, Domain und Hosting.</li><li><strong>Launch und Pflege</strong> — Live-Gang; Änderungen danach auf Wunsch.</li></ol><p>Sie wissen, woran wir gerade arbeiten.</p>",
    "faq.packages.q": "Welche Pakete gibt es — und was kosten sie?",
    "faq.packages.a": "<p>Drei Pakete als Orientierung, keine behaupteten Marktpreise. Der genaue Preis folgt aus Umfang und Sprachen.</p><ul><li><strong>Starter</strong> — One Page, ab €399. Für Freelancer und sehr kleine Betriebe: Design, mobil, Formular, WhatsApp, Domain-Anbindung.</li><li><strong>Business</strong> — professionelle Website, ab €899. Bis zu fünf Seiten, SEO-Grundlagen, Formular, Karten, Analytics.</li><li><strong>Multilingual</strong> — ab €1.290. Deutsch plus eine weitere Sprache, RTL wo nötig, Sprachumschaltung, SEO je Sprache, passende Typografie.</li></ul><p>Die Preisseite liegt unter <a href=\"/preise/\">/preise</a>.</p>",
    "faq.whatsapp.q": "Kann ich per WhatsApp schreiben?",
    "faq.whatsapp.a": "Ja. Nutzen Sie die auf der Website veröffentlichte Nummer. Aktuell ist das +93 74 797 0495. Eine deutsche +49-Nummer setzen wir ein, sobald sie vorliegt — wir tragen keine erfundene Nummer ein. Das Erstgespräch ist kostenlos. Rückmeldung: innerhalb von 24 Stunden.",
    "faq.timeline.q": "Wie lange dauert eine Website?",
    "faq.timeline.a": "Das hängt vom Umfang ab. Eine One-Page ist in der Regel schneller als eine mehrseitige, zweisprachige Site mit RTL. Einen verbindlichen Termin nennen wir nach dem Erstgespräch, wenn der Umfang klar ist. Wir versprechen keine «Website in zwei Tagen». Auf Anfragen antworten wir innerhalb von 24 Stunden.",
    "faq.munich.q": "Arbeitet ihr nur in München?",
    "faq.munich.a": "München ist unser Bezug. Wir helfen Betrieben in München und in Deutschland — lokal und international bzw. migrantisch. Diese Seite behauptet kein erfundenes Büro und keine erfundene Firmengeschichte.",
    "faq.ownership.q": "Wem gehört die fertige Website?",
    "faq.ownership.a": "Ihnen. Sie bekommen die Dateien, nicht nur einen Login.",
    "faq.texts.q": "Muss ich die Texte selbst schreiben?",
    "faq.texts.a": "Sie kennen das Geschäft; wir helfen bei Struktur, Klarheit und mehrsprachigem Satz. Abstimmung auf Deutsch, Englisch, Dari oder Farsi. Eine beeidigte Übersetzung ist ein eigener Schritt, wenn Sie sie brauchen — die behaupten wir nicht automatisch mit.",
    "faq.proof.q": "Gibt es Kundenstimmen?",
    "faq.proof.a": "Nur wenn sie echt sind. Wir setzen keine erfundenen Testimonials. Öffentliche Beispiele, die nicht aus einem echten Auftrag stammen, heißen Konzeptprojekt.",
    "faq.start.q": "Wie starte ich?",
    "faq.start.a": "Kostenloses Erstgespräch über das Formular auf der <a href=\"/#contact\">Startseite</a>, per E-Mail oder WhatsApp. Ein paar Sätze zu Betrieb, Sprachen und Ziel reichen.",
    "close.title": "Noch etwas offen?",
    "close.lede": "Schreiben Sie uns. Ein kurzes Gespräch klärt Umfang, Sprachen und ob Starter, Business oder Multilingual passt.",
    "foot.home": "Startseite",
    "foot.about": "Über uns",
  },
  en: {
    "meta.title": "FAQ — languages, process, packages | Peivando",
    "meta.desc": "Straight answers on languages, RTL, process, packages, WhatsApp and timelines. No fake reviews.",
    "skip": "Skip to content",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "langs.label": "Language",
    "eyebrow": "FAQ",
    "title": "Plain answers, no sales theatre.",
    "lede": "Languages, RTL, process, packages, WhatsApp and timelines. Where we cannot publish something yet — a German phone number, for example — we say so.",
    "cta.talk": "Free first conversation",
    "cta.about": "About Peivando",
    "cta.wa": "Message us on WhatsApp",
    "cta.waText": "Hello Peivando, I have a question about a website.",
    "faq.languages.q": "Which languages do you work in?",
    "faq.languages.a": "German, English, Dari (دری) and Farsi (فارسی). Advice, copy and the site itself can run in these languages. Further languages are possible; then we settle translation and typesetting separately. All four languages are selectable on the site.",
    "faq.rtl.q": "What is RTL — and why does it matter?",
    "faq.rtl.a": "Dari and Farsi are read right to left. That affects navigation, forms, spacing and numbers, not only a paragraph of text. A mirrored German page is not an RTL layout. We implement reading direction as layout.",
    "faq.process.q": "How does a project run?",
    "faq.process.a": "<p>Four steps, in this order:</p><ol><li><strong>Talk</strong> — What the business does, who should find you, what is missing today. Free, no obligation.</li><li><strong>Design</strong> — Structure and look, before anything is built.</li><li><strong>Build</strong> — Production, testing on phone, tablet and desktop, domain and hosting.</li><li><strong>Launch and care</strong> — Go-live; changes afterwards if you want them.</li></ol><p>You always know what we are working on.</p>",
    "faq.packages.q": "What packages are there — and what do they cost?",
    "faq.packages.a": "<p>Three packages as orientation, not claimed market prices. The actual price follows scope and languages.</p><ul><li><strong>Starter</strong> — one page, from €399. For freelancers and very small businesses: design, mobile, form, WhatsApp, domain connect.</li><li><strong>Business</strong> — professional site, from €899. Up to five pages, SEO basics, form, maps, analytics.</li><li><strong>Multilingual</strong> — from €1,290. German plus another language, RTL where needed, language switch, SEO per language, fitting typography.</li></ul><p>The pricing page lives at <a href=\"/preise/\">/preise</a>.</p>",
    "faq.whatsapp.q": "Can I write on WhatsApp?",
    "faq.whatsapp.a": "Yes. Use the number published on the site. Right now that is +93 74 797 0495. We will add a German +49 number when we have one — we will not invent it. The first conversation is free. We aim to reply within 24 hours.",
    "faq.timeline.q": "How long does a website take?",
    "faq.timeline.a": "It depends on scope. A one-pager is usually faster than a multi-page, two-language site with RTL. We give a firm date after the first conversation, once scope is clear. We do not promise a “website in two days”. Enquiries get a reply within 24 hours.",
    "faq.munich.q": "Do you only work in Munich?",
    "faq.munich.a": "Munich is our positioning. We help businesses in Munich and across Germany — local and international or migrant. This page does not claim a made-up office or a fabricated company history.",
    "faq.ownership.q": "Who owns the finished website?",
    "faq.ownership.a": "You do. You get the files, not just a login.",
    "faq.texts.q": "Do I have to write the copy myself?",
    "faq.texts.a": "You know the business; we help with structure, clarity and multilingual typesetting. We can talk in German, English, Dari or Farsi. A sworn translation is a separate step if you need one — we do not pretend it is included by default.",
    "faq.proof.q": "Are there testimonials?",
    "faq.proof.a": "Only real ones. We do not publish fake testimonials. Public examples that are not live client work are labelled Konzeptprojekt.",
    "faq.start.q": "How do I start?",
    "faq.start.a": "A free first conversation via the form on the <a href=\"/#contact\">home page</a>, by email or WhatsApp. A few sentences about the business, languages and goal are enough.",
    "close.title": "Still open?",
    "close.lede": "Write to us. A short conversation clarifies scope, languages, and whether Starter, Business or Multilingual fits.",
    "foot.home": "Home",
    "foot.about": "About",
  },
  prs: {
    "meta.title": "پرسش‌ها — زبان، روند، بسته‌ها | پیوندو",
    "meta.desc": "پاسخ روشن به زبان‌ها، راست‌به‌چپ، روند کار، بسته‌ها، واتس‌اپ و زمان. بدون نظر جعلی.",
    "skip": "به محتوا بروید",
    "nav.about": "دربارهٔ ما",
    "nav.faq": "پرسش‌ها",
    "langs.label": "زبان",
    "eyebrow": "پرسش‌ها",
    "title": "پاسخ روشن، بدون نمایش فروش.",
    "lede": "زبان‌ها، راست‌به‌چپ، روند، بسته‌ها، واتس‌اپ و زمان. جایی که هنوز نمی‌توانیم چیزی را علنی کنیم — مثلاً شمارهٔ آلمانی — همان را می‌گوییم.",
    "cta.talk": "گفت‌وگوی نخست رایگان",
    "cta.about": "دربارهٔ پیوندو",
    "cta.wa": "در واتس‌اپ بنویسید",
    "cta.waText": "سلام پیوندو، یک پرسش دربارهٔ وب‌سایت دارم.",
    "faq.languages.q": "به کدام زبان‌ها کار می‌کنید؟",
    "faq.languages.a": "آلمانی، انگلیسی، دری و فارسی. مشوره، متن و خود وب‌سایت می‌تواند به این زبان‌ها باشد. زبان‌های دیگر ممکن است؛ آن وقت ترجمه و حروف‌چینی جدا روشن می‌شود. هر چهار زبان در سایت قابل انتخاب‌اند.",
    "faq.rtl.q": "RTL چیست و چرا مهم است؟",
    "faq.rtl.a": "دری و فارسی از راست به چپ خوانده می‌شوند. این فقط یک بند متن نیست: ناوبری، فرم، فاصله و عدد را هم دربر می‌گیرد. صفحهٔ آلمانی آینه‌شده چیدمان راست‌به‌چپ نیست. ما جهت خواندن را به‌عنوان چیدمان می‌سازیم.",
    "faq.process.q": "پروژه چگونه پیش می‌رود؟",
    "faq.process.a": "<p>چهار گام، به همین ترتیب:</p><ol><li><strong>گفت‌وگو</strong> — کسب‌وکار چه می‌کند، چه کسی باید شما را بیابد، امروز چه کم است. رایگان و بدون تعهد.</li><li><strong>طرح</strong> — ساختار و ظاهر، پیش از ساخت.</li><li><strong>ساخت</strong> — اجرا، آزمایش روی موبایل و تبلت و دسکتاپ، دامنه و میزبانی.</li><li><strong>راه‌اندازی و نگهداری</strong> — زنده شدن سایت؛ بعد از آن تغییر در صورت نیاز.</li></ol><p>شما می‌دانید روی چه کار می‌کنیم.</p>",
    "faq.packages.q": "چه بسته‌هایی هست و قیمت چیست؟",
    "faq.packages.a": "<p>سه بسته برای جهت‌دهی، نه قیمت ادعایی بازار. قیمت دقیق از حجم کار و زبان‌ها می‌آید.</p><ul><li><strong>Starter</strong> — یک صفحه، از ۳۹۹ یورو. برای فریلنسر و کسب‌وکار خیلی کوچک: طراحی، موبایل، فرم، واتس‌اپ، وصل کردن دامنه.</li><li><strong>Business</strong> — سایت حرفه‌ای، از ۸۹۹ یورو. تا پنج صفحه، پایه‌های سئو، فرم، نقشه، آنالیتیکس.</li><li><strong>Multilingual</strong> — از ۱٬۲۹۰ یورو. آلمانی به‌علاوهٔ یک زبان دیگر، راست‌به‌چپ در صورت نیاز، تعویض زبان، سئو برای هر زبان، تایپ مناسب.</li></ul><p>صفحهٔ قیمت: <a href=\"/preise/\">/preise</a>.</p>",
    "faq.whatsapp.q": "می‌توانم در واتس‌اپ بنویسم؟",
    "faq.whatsapp.a": "بله. شمارهٔ منتشرشده در سایت را استفاده کنید. فعلاً +93 74 797 0495 است. شمارهٔ آلمانی +49 را وقتی داشته باشیم می‌گذاریم — شمارهٔ ساختگی نمی‌نویسیم. گفت‌وگوی نخست رایگان است. پاسخ: ظرف ۲۴ ساعت.",
    "faq.timeline.q": "ساخت وب‌سایت چقدر طول می‌کشد؟",
    "faq.timeline.a": "به حجم کار بسته است. یک‌صفحه‌ای معمولاً زودتر از سایت چندصفحه‌ایِ دوزبانه با راست‌به‌چپ تمام می‌شود. تاریخ قطعی را بعد از گفت‌وگوی نخست می‌گوییم، وقتی حجم روشن باشد. «سایت در دو روز» وعده نمی‌دهیم. به پیام‌ها ظرف ۲۴ ساعت جواب می‌دهیم.",
    "faq.munich.q": "فقط در مونیخ کار می‌کنید؟",
    "faq.munich.a": "مونیخ نقطهٔ اتکای ماست. به کسب‌وکارها در مونیخ و در آلمان کمک می‌کنیم — محلی و بین‌المللی یا مهاجر. این صفحه دفتر ساختگی و تاریخچهٔ شرکتی ساختگی ادعا نمی‌کند.",
    "faq.ownership.q": "وب‌سایت تمام‌شده مال کیست؟",
    "faq.ownership.a": "مال شما. فایل‌ها را می‌گیرید، نه فقط یک ورود.",
    "faq.texts.q": "متن را خودم باید بنویسم؟",
    "faq.texts.a": "شما کسب‌وکار را می‌شناسید؛ ما در ساختار، روشنی و حروف‌چینی چندزبانه کمک می‌کنیم. گپ به آلمانی، انگلیسی، دری یا فارسی. ترجمهٔ رسمی/سوگندخورده اگر لازم باشد گام جداست — آن را پیش‌فرض حساب نمی‌کنیم.",
    "faq.proof.q": "نظر مشتری دارید؟",
    "faq.proof.a": "فقط اگر واقعی باشد. نظر ساختگی نمی‌گذاریم. نمونه‌های عمومی که سفارش واقعی نیستند، Konzeptprojekt نام دارند.",
    "faq.start.q": "از کجا شروع کنم؟",
    "faq.start.a": "گفت‌وگوی نخست رایگان از فرم <a href=\"/#contact\">صفحهٔ نخست</a>، ایمیل یا واتس‌اپ. چند جمله دربارهٔ کسب‌وکار، زبان و هدف کافی است.",
    "close.title": "هنوز چیزی مانده؟",
    "close.lede": "برای‌مان بنویسید. یک گپ کوتاه حجم، زبان‌ها و این را روشن می‌کند که Starter، Business یا Multilingual مناسب است.",
    "foot.home": "صفحهٔ نخست",
    "foot.about": "دربارهٔ ما",
  },
  fa: {
    "meta.title": "پرسش‌ها — زبان، روند، بسته‌ها | پیوندو",
    "meta.desc": "پاسخ روشن دربارهٔ زبان‌ها، راست‌به‌چپ، روند کار، بسته‌ها، واتس‌اپ و زمان‌بندی. بدون نظر جعلی.",
    "skip": "رفتن به محتوا",
    "nav.about": "دربارهٔ ما",
    "nav.faq": "پرسش‌ها",
    "langs.label": "زبان",
    "eyebrow": "پرسش‌ها",
    "title": "پاسخ روشن، بدون نمایش فروش.",
    "lede": "زبان‌ها، راست‌به‌چپ، روند، بسته‌ها، واتس‌اپ و زمان. جایی که هنوز نمی‌توانیم چیزی را علنی کنیم — مثلاً شمارهٔ آلمانی — همان را می‌گوییم.",
    "cta.talk": "گفت‌وگوی اول رایگان",
    "cta.about": "دربارهٔ پیوندو",
    "cta.wa": "پیام در واتس‌اپ",
    "cta.waText": "سلام پیوندو، دربارهٔ وب‌سایت سؤال دارم.",
    "faq.languages.q": "با کدام زبان‌ها کار می‌کنید؟",
    "faq.languages.a": "آلمانی، انگلیسی، دری و فارسی. مشاوره، متن و خود وب‌سایت می‌تواند به این زبان‌ها باشد. زبان‌های دیگر ممکن است؛ آن‌وقت ترجمه و حروف‌چینی جدا هماهنگ می‌شود. هر چهار زبان در سایت قابل انتخاب هستند.",
    "faq.rtl.q": "RTL چیست و چرا اهمیت دارد؟",
    "faq.rtl.a": "دری و فارسی از راست به چپ خوانده می‌شوند. این فقط یک بند متن نیست: ناوبری، فرم، فاصله‌ها و اعداد را هم شامل می‌شود. صفحهٔ آلمانی آینه‌شده چیدمان راست‌به‌چپ نیست. ما جهت خواندن را به‌عنوان چیدمان پیاده می‌کنیم.",
    "faq.process.q": "روند پروژه چگونه است؟",
    "faq.process.a": "<p>چهار گام، به همین ترتیب:</p><ol><li><strong>گفت‌وگو</strong> — کسب‌وکار چه می‌کند، چه کسی باید شما را پیدا کند، امروز چه چیزی کم است. رایگان و بدون تعهد.</li><li><strong>طرح</strong> — ساختار و ظاهر، پیش از ساخت.</li><li><strong>ساخت</strong> — اجرا، آزمایش روی موبایل، تبلت و دسکتاپ، دامنه و میزبانی.</li><li><strong>راه‌اندازی و نگهداری</strong> — انتشار؛ پس از آن در صورت نیاز تغییر.</li></ol><p>همیشه می‌دانید روی چه چیزی کار می‌کنیم.</p>",
    "faq.packages.q": "چه بسته‌هایی هست و هزینه چیست؟",
    "faq.packages.a": "<p>سه بسته برای جهت‌گیری، نه قیمت ادعایی بازار. قیمت دقیق از حجم کار و زبان‌ها می‌آید.</p><ul><li><strong>Starter</strong> — یک صفحه، از ۳۹۹ یورو. برای فریلنسر و کسب‌وکار خیلی کوچک: طراحی، موبایل، فرم، واتس‌اپ، اتصال دامنه.</li><li><strong>Business</strong> — سایت حرفه‌ای، از ۸۹۹ یورو. تا پنج صفحه، پایه‌های سئو، فرم، نقشه، آنالیتیکس.</li><li><strong>Multilingual</strong> — از ۱٬۲۹۰ یورو. آلمانی به‌علاوهٔ یک زبان دیگر، راست‌به‌چپ در صورت نیاز، تغییر زبان، سئو برای هر زبان، تایپ مناسب.</li></ul><p>صفحهٔ قیمت: <a href=\"/preise/\">/preise</a>.</p>",
    "faq.whatsapp.q": "می‌توانم در واتس‌اپ پیام بدهم؟",
    "faq.whatsapp.a": "بله. از شمارهٔ منتشرشده در سایت استفاده کنید. فعلاً +93 74 797 0495 است. شمارهٔ آلمانی +۴۹ را وقتی داشته باشیم اضافه می‌کنیم — شمارهٔ ساختگی نمی‌نویسیم. گفت‌وگوی اول رایگان است. پاسخ: ظرف ۲۴ ساعت.",
    "faq.timeline.q": "ساخت وب‌سایت چقدر طول می‌کشد؟",
    "faq.timeline.a": "به محدودهٔ کار بستگی دارد. یک صفحه معمولاً زودتر از سایت چندصفحه‌ای دوزبانه با راست‌به‌چپ تمام می‌شود. تاریخ قطعی را بعد از گفت‌وگوی اول می‌گوییم، وقتی محدوده روشن باشد. «وب‌سایت در دو روز» وعده نمی‌دهیم. به پیام‌ها ظرف ۲۴ ساعت پاسخ می‌دهیم.",
    "faq.munich.q": "فقط در مونیخ کار می‌کنید؟",
    "faq.munich.a": "مونیخ نقطهٔ اتکای ماست. به کسب‌وکارها در مونیخ و در آلمان کمک می‌کنیم — محلی و بین‌المللی یا مهاجر. این صفحه دفتر ساختگی و تاریخچهٔ شرکتی ساختگی ادعا نمی‌کند.",
    "faq.ownership.q": "وب‌سایت تمام‌شده متعلق به کیست؟",
    "faq.ownership.a": "متعلق به شما. فایل‌ها را می‌گیرید، نه فقط یک ورود.",
    "faq.texts.q": "متن را خودم باید بنویسم؟",
    "faq.texts.a": "شما کسب‌وکار را می‌شناسید؛ ما در ساختار، وضوح و حروف‌چینی چندزبانه کمک می‌کنیم. هماهنگی به آلمانی، انگلیسی، دری یا فارسی. ترجمهٔ رسمی در صورت نیاز گام جداگانه‌ای است — آن را به‌طور پیش‌فرض شامل نمی‌دانیم.",
    "faq.proof.q": "نظر مشتری دارید؟",
    "faq.proof.a": "فقط اگر واقعی باشد. نظر ساختگی منتشر نمی‌کنیم. نمونه‌های عمومی که سفارش واقعی نیستند با برچسب Konzeptprojekt مشخص می‌شوند.",
    "faq.start.q": "چطور شروع کنم؟",
    "faq.start.a": "گفت‌وگوی اول رایگان از فرم <a href=\"/#contact\">صفحهٔ اصلی</a>، ایمیل یا واتس‌اپ. چند جمله دربارهٔ کسب‌وکار، زبان‌ها و هدف کافی است.",
    "close.title": "هنوز سؤالی مانده؟",
    "close.lede": "برای ما بنویسید. یک گفت‌وگوی کوتاه محدوده، زبان‌ها و تناسب Starter، Business یا Multilingual را روشن می‌کند.",
    "foot.home": "خانه",
    "foot.about": "دربارهٔ ما",
  },
};

export function getFaqCopy(lang) {
  return faqCopy[lang] || faqCopy.de;
}

export function getFaqItems(lang) {
  const dict = getFaqCopy(lang);
  return FAQ_IDS.map(function (id) {
    return {
      id: id,
      question: dict["faq." + id + ".q"],
      answer: dict["faq." + id + ".a"],
    };
  });
}
