export const COPY = {
  de: {
    eyebrow: "Preise",
    title: "Drei Pakete. Preise in Euro.",
    lede: "Für Freelancer, kleine Betriebe und Unternehmen, deren Kundinnen und Kunden verschiedene Sprachen sprechen. Startpreise — das genaue Angebot folgt nach dem Gespräch.",
    meta1: "Startpreise in Euro",
    meta2: "Erstgespräch kostenlos",
    meta3: "Persönliche Betreuung",
    from: "ab",
    once: "einmalig",
    featured: "Für die meisten Betriebe",
    ctaPrimary: "Kostenloses Erstgespräch",
    ctaCard: "Dieses Paket anfragen",
    ctaWhatsapp: "Per WhatsApp schreiben",
    waText: "Hallo Peivando, ich interessiere mich für das Paket {name}.",
    notesTitle: "Klarheit vor dem Angebot",
    notes: [
      "Keine durchgestrichenen Preise und keine Scheinrabatte.",
      "Domain-Registrierung und Hosting sind nicht im Paketpreis. Wir binden Ihre Domain an.",
      "Mehrsprachig meint Deutsch plus eine weitere Sprache. Weitere Sprachen auf Anfrage.",
    ],
    packages: {
      starter: {
        name: "Starter",
        kind: "One Page",
        audience: "Freelancer und kleine Betriebe",
      },
      business: {
        name: "Business",
        kind: "Professionelle Website",
        audience: "Bis zu fünf Seiten, fundiert aufgebaut",
      },
      multilingual: {
        name: "Mehrsprachig",
        kind: "Deutsch plus eine Sprache",
        audience: "Betriebe mit gemischtem Publikum",
      },
    },
    features: {
      design: "Design und Aufbau",
      mobile: "Mobilfreundlich",
      form: "Kontaktformular",
      whatsapp: "WhatsApp-Button",
      domain: "Domain anbinden",
      pages5: "Bis zu fünf Seiten",
      responsive: "Responsive auf Handy, Tablet und Desktop",
      seo: "SEO-Grundlagen",
      maps: "Google Maps",
      analytics: "Analytics",
      dePlusOne: "Deutsch plus eine weitere Sprache",
      rtl: "Echtes RTL-Layout",
      switcher: "Sprachumschaltung",
      seoLang: "SEO je Sprache",
      typography: "Typografie, die zur Schrift passt",
    },
  },
  en: {
    eyebrow: "Pricing",
    title: "Three packages. Prices in euro.",
    lede: "For freelancers, small businesses, and companies whose customers speak more than one language. Starting prices — the exact quote comes after we talk.",
    meta1: "Starting prices in euro",
    meta2: "First conversation free",
    meta3: "Personal support",
    from: "from",
    once: "one-off",
    featured: "Fits most businesses",
    ctaPrimary: "Book a free first call",
    ctaCard: "Ask about this package",
    ctaWhatsapp: "Message us on WhatsApp",
    waText: "Hello Peivando, I'm interested in the {name} package.",
    notesTitle: "Clear before the quote",
    notes: [
      "No struck-through prices and no fake discounts.",
      "Domain registration and hosting are not in the package price. We connect the domain you already have.",
      "Multilingual means German plus one other language. Further languages on request.",
    ],
    packages: {
      starter: {
        name: "Starter",
        kind: "One page",
        audience: "Freelancers and small businesses",
      },
      business: {
        name: "Business",
        kind: "Professional site",
        audience: "Up to five pages, built properly",
      },
      multilingual: {
        name: "Multilingual",
        kind: "German plus one language",
        audience: "Businesses with a mixed audience",
      },
    },
    features: {
      design: "Design and build",
      mobile: "Mobile-friendly",
      form: "Contact form",
      whatsapp: "WhatsApp button",
      domain: "Domain connect",
      pages5: "Up to five pages",
      responsive: "Responsive on phone, tablet and desktop",
      seo: "SEO basics",
      maps: "Google Maps",
      analytics: "Analytics",
      dePlusOne: "German plus one other language",
      rtl: "Real RTL layout",
      switcher: "Language switch",
      seoLang: "SEO per language",
      typography: "Typography that fits the script",
    },
  },
  fa: {
    eyebrow: "قیمت‌ها",
    title: "سه بسته. قیمت‌ها به یورو.",
    lede: "برای فریلنسرها، کسب‌وکارهای کوچک و شرکت‌هایی که مشتری‌شان بیش از یک زبان حرف می‌زند. قیمت‌های شروع — پیشنهاد دقیق بعد از گفت‌وگو می‌آید.",
    meta1: "قیمت شروع به یورو",
    meta2: "نخستین گفت‌وگو رایگان",
    meta3: "پشتیبانی شخصی",
    from: "از",
    once: "یک‌باره",
    featured: "برای بیشتر کسب‌وکارها",
    ctaPrimary: "گفت‌وگوی نخست رایگان",
    ctaCard: "دربارهٔ این بسته بپرسید",
    ctaWhatsapp: "در واتس‌اپ پیام بفرستید",
    waText: "سلام پیوندو، به بستهٔ {name} علاقه‌مند هستم.",
    notesTitle: "قبل از پیشنهاد، روشن",
    notes: [
      "بدون قیمت خط‌خورده و بدون تخفیف نمایشی.",
      "ثبت دامنه و میزبانی در قیمت بسته نیست. دامنهٔ شما را وصل می‌کنیم.",
      "چندزبانه یعنی آلمانی به اضافهٔ یک زبان دیگر. زبان‌های بیشتر بر اساس توافق.",
    ],
    packages: {
      starter: {
        name: "Starter",
        kind: "یک صفحه",
        audience: "فریلنسرها و کسب‌وکارهای کوچک",
      },
      business: {
        name: "Business",
        kind: "وب‌سایت حرفه‌ای",
        audience: "تا پنج صفحه، درست ساخته‌شده",
      },
      multilingual: {
        name: "چندزبانه",
        kind: "آلمانی به اضافهٔ یک زبان",
        audience: "کسب‌وکارهایی با مخاطب چندزبانه",
      },
    },
    features: {
      design: "طراحی و ساخت",
      mobile: "سازگار با موبایل",
      form: "فرم تماس",
      whatsapp: "دکمهٔ واتس‌اپ",
      domain: "اتصال دامنه",
      pages5: "تا پنج صفحه",
      responsive: "واکنش‌گرا روی موبایل، تبلت و دسکتاپ",
      seo: "مبانی سئو",
      maps: "گوگل مپس",
      analytics: "آنالیتیکس",
      dePlusOne: "آلمانی به اضافهٔ یک زبان دیگر",
      rtl: "چیدمان واقعی راست‌به‌چپ",
      switcher: "تعویض زبان",
      seoLang: "سئو برای هر زبان",
      typography: "حروف‌چینی متناسب با خط",
    },
  },
};

COPY.prs = COPY.fa;
