export const CONTACT_STRINGS = {
  de: {
    "meta.title": "Kontakt — Peivando",
    "skip": "Zum Formular",
    "brand.home": "Zur Startseite",
    "lang.group": "Sprache der Seite",
    "con.eyebrow": "Kontakt",
    "con.title": "Was soll Ihre Website leisten?",
    "con.lede":
      "Wählen Sie Bedarf, Umfang, Sprachen und Budget. Wir antworten innerhalb von 24 Stunden — auf Deutsch, Englisch, Dari oder Farsi.",
    "con.mail": "E-Mail",
    "recap.label": "Ihre Auswahl",
    "recap.empty": "Noch keine Auswahl.",
    "f.need": "Was brauchen Sie?",
    "f.need.new": "Neue Website",
    "f.need.redesign": "Redesign",
    "f.need.landing": "Landing Page",
    "f.need.multilingual": "Mehrsprachige Website",
    "f.need.care": "Pflege / Betreuung",
    "f.pages": "Wie viele Seiten?",
    "f.pages.1": "1 Seite (One-Pager)",
    "f.pages.2-5": "2–5 Seiten",
    "f.pages.6-10": "6–10 Seiten",
    "f.pages.unsure": "Noch unsicher",
    "f.langs": "In welchen Sprachen?",
    "f.langs.hint": "Mehrfachauswahl möglich.",
    "f.langs.de": "Deutsch",
    "f.langs.en": "Englisch",
    "f.langs.prs": "دری (Dari)",
    "f.langs.fa": "فارسی (Farsi)",
    "f.langs.err": "Bitte mindestens eine Sprache wählen.",
    "f.budget": "Welches Budget haben Sie im Blick?",
    "f.budget.0-500": "bis 500 €",
    "f.budget.500-1000": "500–1.000 €",
    "f.budget.1000-2000": "1.000–2.000 €",
    "f.budget.2000+": "über 2.000 €",
    "f.budget.unsure": "Noch unsicher",
    "f.name": "Name",
    "f.mail": "E-Mail oder Telefon",
    "f.notes": "Sonst noch etwas? (optional)",
    "f.send": "Kostenloses Angebot erhalten",
    "f.privacy":
      "Ihre Angaben werden nur zur Beantwortung Ihrer Anfrage verwendet.",
    "f.privacy.link": "Datenschutzerklärung",
    "f.miss": "Bitte Name, Kontakt und die Angaben zur Website ausfüllen.",
    "f.off":
      "Das Formular ist noch nicht verbunden. Schreiben Sie uns solange direkt per WhatsApp oder E-Mail.",
    "f.err":
      "Das hat nicht geklappt. Bitte schreiben Sie uns direkt per WhatsApp oder E-Mail.",
    "f.sent":
      "Danke — Ihre Anfrage ist angekommen. Wir melden uns innerhalb von 24 Stunden.",
    "wa.prefill":
      "Hallo Peivando, ich möchte ein kostenloses Angebot für eine Website.",
  },
  en: {
    "meta.title": "Contact — Peivando",
    "skip": "Skip to form",
    "brand.home": "Back to home",
    "lang.group": "Page language",
    "con.eyebrow": "Contact",
    "con.title": "What should your website do?",
    "con.lede":
      "Choose what you need, page count, languages and budget. We reply within 24 hours — in German, English, Dari or Farsi.",
    "con.mail": "Email",
    "recap.label": "Your selection",
    "recap.empty": "Nothing selected yet.",
    "f.need": "What do you need?",
    "f.need.new": "New website",
    "f.need.redesign": "Redesign",
    "f.need.landing": "Landing page",
    "f.need.multilingual": "Multilingual website",
    "f.need.care": "Care / maintenance",
    "f.pages": "How many pages?",
    "f.pages.1": "1 page (one-pager)",
    "f.pages.2-5": "2–5 pages",
    "f.pages.6-10": "6–10 pages",
    "f.pages.unsure": "Not sure yet",
    "f.langs": "Which languages?",
    "f.langs.hint": "You can select more than one.",
    "f.langs.de": "German",
    "f.langs.en": "English",
    "f.langs.prs": "دری (Dari)",
    "f.langs.fa": "فارسی (Farsi)",
    "f.langs.err": "Please choose at least one language.",
    "f.budget": "What budget do you have in mind?",
    "f.budget.0-500": "up to €500",
    "f.budget.500-1000": "€500–€1,000",
    "f.budget.1000-2000": "€1,000–€2,000",
    "f.budget.2000+": "over €2,000",
    "f.budget.unsure": "Not sure yet",
    "f.name": "Name",
    "f.mail": "Email or phone",
    "f.notes": "Anything else? (optional)",
    "f.send": "Get a free quote",
    "f.privacy": "Your details are used only to answer your enquiry.",
    "f.privacy.link": "Privacy policy",
    "f.miss": "Please fill in name, contact and the website details.",
    "f.off":
      "The form isn’t connected yet. Please write to us on WhatsApp or by email in the meantime.",
    "f.err":
      "That didn’t go through. Please write to us on WhatsApp or by email.",
    "f.sent":
      "Thank you — your enquiry has arrived. We’ll reply within 24 hours.",
    "wa.prefill":
      "Hello Peivando, I’d like a free quote for a website.",
  },
  prs: {
    "meta.title": "تماس — پیوندو",
    "skip": "به فرم بروید",
    "brand.home": "بازگشت به صفحهٔ نخست",
    "lang.group": "زبان صفحه",
    "con.eyebrow": "تماس",
    "con.title": "وب‌سایت‌تان چه کاری باید بکند؟",
    "con.lede":
      "نیاز، تعداد صفحات، زبان‌ها و بودجه را انتخاب کنید. ظرف ۲۴ ساعت پاسخ می‌دهیم — به آلمانی، انگلیسی، دری یا فارسی.",
    "con.mail": "ایمیل",
    "recap.label": "انتخاب شما",
    "recap.empty": "هنوز چیزی انتخاب نشده است.",
    "f.need": "به چه چیزی نیاز دارید؟",
    "f.need.new": "وب‌سایت جدید",
    "f.need.redesign": "طراحی مجدد",
    "f.need.landing": "صفحهٔ فرود",
    "f.need.multilingual": "وب‌سایت چندزبانه",
    "f.need.care": "مراقبت و نگهداری",
    "f.pages": "چند صفحه؟",
    "f.pages.1": "۱ صفحه (یک‌صفحه‌ای)",
    "f.pages.2-5": "۲ تا ۵ صفحه",
    "f.pages.6-10": "۶ تا ۱۰ صفحه",
    "f.pages.unsure": "هنوز مطمئن نیستم",
    "f.langs": "به کدام زبان‌ها؟",
    "f.langs.hint": "می‌توانید چند زبان انتخاب کنید.",
    "f.langs.de": "آلمانی",
    "f.langs.en": "انگلیسی",
    "f.langs.prs": "دری",
    "f.langs.fa": "فارسی",
    "f.langs.err": "لطفاً حداقل یک زبان را انتخاب کنید.",
    "f.budget": "بودجهٔ مورد نظر شما چیست؟",
    "f.budget.0-500": "تا ۵۰۰ یورو",
    "f.budget.500-1000": "۵۰۰ تا ۱٬۰۰۰ یورو",
    "f.budget.1000-2000": "۱٬۰۰۰ تا ۲٬۰۰۰ یورو",
    "f.budget.2000+": "بیش از ۲٬۰۰۰ یورو",
    "f.budget.unsure": "هنوز مطمئن نیستم",
    "f.name": "نام",
    "f.mail": "ایمیل یا تلفن",
    "f.notes": "چیز دیگری؟ (اختیاری)",
    "f.send": "پیشنهاد رایگان بگیرید",
    "f.privacy":
      "اطلاعات شما فقط برای پاسخ به درخواست‌تان استفاده می‌شود.",
    "f.privacy.link": "حفاظت از داده‌ها",
    "f.miss": "لطفاً نام، راه تماس و جزئیات وب‌سایت را پر کنید.",
    "f.off":
      "فرم هنوز وصل نشده است. در این میان لطفاً از واتس‌اپ یا ایمیل بنویسید.",
    "f.err": "ارسال نشد. لطفاً از واتس‌اپ یا ایمیل بنویسید.",
    "f.sent": "سپاس — درخواست شما رسید. ظرف ۲۴ ساعت پاسخ می‌دهیم.",
    "wa.prefill":
      "سلام پیوندو، می‌خواهم برای یک وب‌سایت پیشنهاد رایگان بگیرم.",
  },
  fa: {
    "meta.title": "تماس — پیوندو",
    "skip": "رفتن به فرم",
    "brand.home": "بازگشت به صفحهٔ اصلی",
    "lang.group": "زبان صفحه",
    "con.eyebrow": "تماس",
    "con.title": "وب‌سایت‌تان باید چه کاری انجام دهد؟",
    "con.lede":
      "نیاز، تعداد صفحات، زبان‌ها و بودجه را مشخص کنید. ظرف ۲۴ ساعت پاسخ می‌دهیم — به آلمانی، انگلیسی، دری یا فارسی.",
    "con.mail": "ایمیل",
    "recap.label": "انتخاب شما",
    "recap.empty": "هنوز چیزی انتخاب نشده.",
    "f.need": "به چه چیزی نیاز دارید؟",
    "f.need.new": "وب‌سایت تازه",
    "f.need.redesign": "بازطراحی",
    "f.need.landing": "لندینگ‌پیج",
    "f.need.multilingual": "وب‌سایت چندزبانه",
    "f.need.care": "نگهداری و پشتیبانی",
    "f.pages": "چند صفحه؟",
    "f.pages.1": "۱ صفحه (تک‌صفحه)",
    "f.pages.2-5": "۲ تا ۵ صفحه",
    "f.pages.6-10": "۶ تا ۱۰ صفحه",
    "f.pages.unsure": "هنوز مطمئن نیستم",
    "f.langs": "به کدام زبان‌ها؟",
    "f.langs.hint": "می‌توانید چند مورد را انتخاب کنید.",
    "f.langs.de": "آلمانی",
    "f.langs.en": "انگلیسی",
    "f.langs.prs": "دری",
    "f.langs.fa": "فارسی",
    "f.langs.err": "لطفاً دست‌کم یک زبان را انتخاب کنید.",
    "f.budget": "بودجهٔ مدنظرتان چقدر است؟",
    "f.budget.0-500": "تا ۵۰۰ یورو",
    "f.budget.500-1000": "۵۰۰ تا ۱٬۰۰۰ یورو",
    "f.budget.1000-2000": "۱٬۰۰۰ تا ۲٬۰۰۰ یورو",
    "f.budget.2000+": "بیش از ۲٬۰۰۰ یورو",
    "f.budget.unsure": "هنوز مطمئن نیستم",
    "f.name": "نام",
    "f.mail": "ایمیل یا تلفن",
    "f.notes": "نکتهٔ دیگری؟ (اختیاری)",
    "f.send": "دریافت پیشنهاد رایگان",
    "f.privacy":
      "اطلاعات شما فقط برای پاسخ به درخواست‌تان استفاده می‌شود.",
    "f.privacy.link": "حریم خصوصی",
    "f.miss": "لطفاً نام، راه تماس و جزئیات وب‌سایت را پر کنید.",
    "f.off":
      "فرم هنوز متصل نشده است. فعلاً از واتس‌اپ یا ایمیل بنویسید.",
    "f.err": "ارسال نشد. لطفاً از واتس‌اپ یا ایمیل بنویسید.",
    "f.sent": "سپاس — درخواست شما رسید. ظرف ۲۴ ساعت پاسخ می‌دهیم.",
    "wa.prefill":
      "سلام پیوندو، می‌خواهم برای یک وب‌سایت پیشنهاد رایگان بگیرم.",
  },
};

export const UI_LANG_ATTR = {
  de: { lang: "de", dir: "ltr" },
  en: { lang: "en", dir: "ltr" },
  prs: { lang: "fa-AF", dir: "rtl" },
  fa: { lang: "fa-IR", dir: "rtl" },
};
