export const aboutCopy = {
  de: {
    "meta.title": "Über Peivando — mehrsprachige Websites für Betriebe in München",
    "meta.desc": "Peivando bedeutet verbinden. Mehrsprachige digitale Hilfe für lokale und internationale Betriebe in Deutschland — Deutsch, Englisch, Dari und Farsi.",
    "skip": "Zum Inhalt",
    "nav.about": "Über uns",
    "nav.faq": "FAQ",
    "langs.label": "Sprache",
    "eyebrow": "Über Peivando · München",
    "title": "Mehrsprachige digitale Hilfe für <em>lokale und internationale</em> Betriebe in Deutschland.",
    "lede": "Peivando bedeutet verbinden. Wir bauen Websites, die auf Deutsch, Englisch, Dari und Farsi funktionieren — damit Kundinnen und Kunden Sie finden, anfragen und kommen. Technisch sauber, persönlich betreut.",
    "cta.talk": "Kostenloses Erstgespräch",
    "cta.faq": "Fragen und Antworten",
    "cta.wa": "Per WhatsApp schreiben",
    "cta.waText": "Hallo Peivando, ich interessiere mich für eine Website.",
    "meaning.eyebrow": "Der Name",
    "meaning.title": "Peivando bedeutet verbinden.",
    "meaning.body": "Auf Persisch steht «پیوند» (peyvand) für Verbindung, Bund, Link. Der Name ist das Versprechen: eine Website soll Ihr Angebot mit den Menschen verbinden, die Sie suchen — in der Sprache, die sie lesen. Nicht als nachträglich übersetzter Zusatz, sondern von Anfang an.",
    "audience.eyebrow": "Für wen",
    "audience.title": "Lokale und migrantische Unternehmen in Deutschland.",
    "audience.lede": "Kleine Betriebe, Praxen und Läden — besonders in und um München, und überall dort, wo die Kundschaft verschiedene Sprachen spricht. Die Liste ist eine Branchenorientierung, keine Kundenliste.",
    "audience.chips": "<span>Restaurant</span><span>Arztpraxis</span><span>Kanzlei</span><span>Fahrschule</span><span>Handwerk</span><span>Autohändler</span><span>Reisebüro</span><span>Steuerberatung</span><span>Salon</span><span>Café</span><span>Einzelhandel</span><span>Immobilien</span><span>Reinigung</span><span>Pflege</span>",
    "audience.note": "Keine erfundenen Referenzen. Wenn ein öffentliches Beispiel kein echter Auftrag ist, heißt es Konzeptprojekt.",
    "work.eyebrow": "Wie wir arbeiten",
    "work.title": "Woran wir uns halten.",
    "work.1.t": "Mehrsprachig",
    "work.1.d": "Deutsch, Englisch, Dari und Farsi. Echtes RTL-Layout, passende Schriften, eine Sprachumschaltung, die die Seite wirklich trägt.",
    "work.2.t": "Technisch sauber",
    "work.2.d": "Mobil, klar, ohne Effekt-Theater. Sie bekommen die Dateien — nicht nur einen Login.",
    "work.3.t": "Persönlich betreut",
    "work.3.d": "Gespräch und Abstimmung in Ihrer Sprache. Kostenloses Erstgespräch, Rückmeldung innerhalb von 24 Stunden.",
    "honest.eyebrow": "Ehrlich",
    "honest.title": "Ohne erfundene Biografie.",
    "honest.body": "Diese Seite zeigt kein Teamfoto, keinen erfundenen Lebenslauf und keine Fake-Bewertungen. München ist unser Bezug — nicht eine erfundene Firmengeschichte. Vertrauen soll über klare Leistung, nachvollziehbare Pakete und ehrliche Projektkennzeichnung entstehen.",
    "close.title": "Erst sprechen, dann bauen.",
    "close.lede": "Ein paar Sätze zu Ihrem Betrieb, den Sprachen Ihrer Kundschaft und dem Ziel der Website reichen. Unverbindlich.",
    "foot.home": "Startseite",
    "foot.faq": "FAQ",
  },
  en: {
    "meta.title": "About Peivando — multilingual websites for businesses in Munich",
    "meta.desc": "Peivando means to connect. Multilingual digital help for local and international businesses in Germany — German, English, Dari and Farsi.",
    "skip": "Skip to content",
    "nav.about": "About",
    "nav.faq": "FAQ",
    "langs.label": "Language",
    "eyebrow": "About Peivando · Munich",
    "title": "Multilingual digital help for <em>local and international</em> businesses in Germany.",
    "lede": "Peivando means to connect. We build websites that work in German, English, Dari and Farsi — so customers can find you, enquire, and show up. Technically clean, personally supported.",
    "cta.talk": "Free first conversation",
    "cta.faq": "Questions and answers",
    "cta.wa": "Message us on WhatsApp",
    "cta.waText": "Hello Peivando, I'm interested in a website.",
    "meaning.eyebrow": "The name",
    "meaning.title": "Peivando means to connect.",
    "meaning.body": "In Persian, «پیوند» (peyvand) is a bond, a link, a connection. The name is the job: a website should connect what you offer with the people looking for it — in the language they read. Not a translation bolted on afterwards. Built in from the start.",
    "audience.eyebrow": "Who it's for",
    "audience.title": "Local and migrant businesses in Germany.",
    "audience.lede": "Small firms, practices and shops — especially in and around Munich, and anywhere customers speak more than one language. The list is a sector orientation, not a client roster.",
    "audience.chips": "<span>Restaurant</span><span>Medical practice</span><span>Law office</span><span>Driving school</span><span>Trades</span><span>Car dealer</span><span>Travel</span><span>Tax advisor</span><span>Salon</span><span>Café</span><span>Retail</span><span>Real estate</span><span>Cleaning</span><span>Care</span>",
    "audience.note": "No invented references. Public examples that are not live client work are labelled Konzeptprojekt.",
    "work.eyebrow": "How we work",
    "work.title": "What we stand by.",
    "work.1.t": "Multilingual",
    "work.1.d": "German, English, Dari and Farsi. Real RTL layout, fitting type, a language switch the site actually runs on.",
    "work.2.t": "Technically clean",
    "work.2.d": "Mobile, clear, no effects for their own sake. You get the files — not just a login.",
    "work.3.t": "Personally supported",
    "work.3.d": "Talk and review in your language. First conversation free, a reply within 24 hours.",
    "honest.eyebrow": "Straight",
    "honest.title": "No invented biography.",
    "honest.body": "This page has no team photo, no made-up résumé and no fake reviews. Munich is our positioning — not a fabricated company history. Trust should come from clear work, readable packages, and honest project labels.",
    "close.title": "Talk first, then build.",
    "close.lede": "A few sentences about your business, the languages your customers use, and what the site should do is enough. No obligation.",
    "foot.home": "Home",
    "foot.faq": "FAQ",
  },
  prs: {
    "meta.title": "دربارهٔ پیوندو — وب‌سایت چندزبانه برای کسب‌وکارها در مونیخ",
    "meta.desc": "پیوندو یعنی وصل شدن. کمک دیجیتال چندزبانه برای کسب‌وکارهای محلی و بین‌المللی در آلمان — آلمانی، انگلیسی، دری و فارسی.",
    "skip": "به محتوا بروید",
    "nav.about": "دربارهٔ ما",
    "nav.faq": "پرسش‌ها",
    "langs.label": "زبان",
    "eyebrow": "دربارهٔ پیوندو · مونیخ",
    "title": "کمک دیجیتال چندزبانه برای کسب‌وکارهای <em>محلی و بین‌المللی</em> در آلمان.",
    "lede": "پیوندو یعنی وصل شدن. وب‌سایت می‌سازیم که به آلمانی، انگلیسی، دری و فارسی کار کند — تا مشتری شما را پیدا کند، پیام بفرستد و بیاید. از نظر فنی تمیز، با همراهی شخصی.",
    "cta.talk": "گفت‌وگوی نخست رایگان",
    "cta.faq": "پرسش و پاسخ",
    "cta.wa": "در واتس‌اپ بنویسید",
    "cta.waText": "سلام پیوندو، من به یک وب‌سایت علاقه‌مند هستم.",
    "meaning.eyebrow": "نام",
    "meaning.title": "پیوندو یعنی وصل شدن.",
    "meaning.body": "در فارسی «پیوند» به معنی اتصال، بند و رابطه است. نام همان کار است: وب‌سایت باید پیشنهاد شما را به کسانی وصل کند که دنبال‌تان می‌گردند — به زبانی که می‌خوانند. نه ترجمه‌ای که بعداً چسبانده شود. از همان ابتدا.",
    "audience.eyebrow": "برای کی",
    "audience.title": "کسب‌وکارهای محلی و مهاجر در آلمان.",
    "audience.lede": "دوکان‌ها، مطب‌ها و شرکت‌های کوچک — به‌ویژه در مونیخ و اطراف آن، و هر جا که مشتری چند زبان حرف می‌زند. این فهرست جهت‌دهی به صنف است، نه لیست مشتری.",
    "audience.chips": "<span>رستوران</span><span>مطب</span><span>دفتر وکالت</span><span>آموزشگاه رانندگی</span><span>حرفه و صنعت</span><span>فروش موتر</span><span>سفر</span><span>مشاورهٔ مالیاتی</span><span>سالن</span><span>کافه</span><span>فروشگاه</span><span>املاک</span><span>نظافت</span><span>مراقبت</span>",
    "audience.note": "مرجع ساختگی نیست. نمونه‌های عمومی که سفارش واقعی نیستند، به‌نام Konzeptprojekt مشخص می‌شوند.",
    "work.eyebrow": "روش کار",
    "work.title": "سه چیزی که نگه می‌داریم.",
    "work.1.t": "چندزبانه",
    "work.1.d": "آلمانی، انگلیسی، دری و فارسی. چیدمان واقعی راست‌به‌چپ، فونت مناسب، تعویض زبانی که واقعاً صفحه را می‌گرداند.",
    "work.2.t": "از نظر فنی تمیز",
    "work.2.d": "سازگار با موبایل، روشن، بدون نمایش اضافی. فایل‌ها را می‌گیرید — نه فقط یک حساب.",
    "work.3.t": "همراهی شخصی",
    "work.3.d": "گفت‌وگو به زبان شما. نخستین صحبت رایگان، پاسخ ظرف ۲۴ ساعت.",
    "honest.eyebrow": "راست",
    "honest.title": "بدون سرگذشت ساختگی.",
    "honest.body": "در این صفحه عکس تیم، زندگی‌نامهٔ ساخته‌شده و نظر جعلی نیست. مونیخ نقطهٔ اتکای ماست — نه تاریخچهٔ شرکتی که وجود ندارد. اعتماد باید از کار روشن، بسته‌های قابل فهم و نام‌گذاری صادقانهٔ پروژه‌ها بیاید.",
    "close.title": "اول گپ، بعد ساخت.",
    "close.lede": "چند جمله دربارهٔ کسب‌وکارتان، زبان مشتری و هدف سایت کافی است. بدون تعهد.",
    "foot.home": "صفحهٔ نخست",
    "foot.faq": "پرسش‌ها",
  },
  fa: {
    "meta.title": "دربارهٔ پیوندو — وب‌سایت چندزبانه برای کسب‌وکارها در مونیخ",
    "meta.desc": "پیوندو یعنی متصل شدن. کمک دیجیتال چندزبانه برای کسب‌وکارهای محلی و بین‌المللی در آلمان — آلمانی، انگلیسی، دری و فارسی.",
    "skip": "رفتن به محتوا",
    "nav.about": "دربارهٔ ما",
    "nav.faq": "پرسش‌ها",
    "langs.label": "زبان",
    "eyebrow": "دربارهٔ پیوندو · مونیخ",
    "title": "کمک دیجیتال چندزبانه برای کسب‌وکارهای <em>محلی و بین‌المللی</em> در آلمان.",
    "lede": "پیوندو یعنی متصل شدن. وب‌سایت‌هایی می‌سازیم که به آلمانی، انگلیسی، دری و فارسی کار می‌کنند — تا مشتری شما را پیدا کند، پیام بگذارد و مراجعه کند. از نظر فنی تمیز، با پشتیبانی شخصی.",
    "cta.talk": "گفت‌وگوی اول رایگان",
    "cta.faq": "پرسش و پاسخ",
    "cta.wa": "پیام در واتس‌اپ",
    "cta.waText": "سلام پیوندو، به یک وب‌سایت علاقه‌مند هستم.",
    "meaning.eyebrow": "نام",
    "meaning.title": "پیوندو یعنی متصل شدن.",
    "meaning.body": "در فارسی «پیوند» یعنی اتصال، پیوند و رابطه. نام همان کار است: وب‌سایت باید پیشنهاد شما را به کسانی وصل کند که به‌دنبال‌تان هستند — به زبانی که می‌خوانند. نه ترجمه‌ای که بعداً اضافه شود. از ابتدا در ساخت.",
    "audience.eyebrow": "برای چه کسانی",
    "audience.title": "کسب‌وکارهای محلی و مهاجر در آلمان.",
    "audience.lede": "فروشگاه‌ها، مطب‌ها و شرکت‌های کوچک — به‌ویژه در مونیخ و اطراف آن، و هر جا که مشتری چند زبان صحبت می‌کند. این فهرست جهت‌گیری صنفی است، نه فهرست مشتری.",
    "audience.chips": "<span>رستوران</span><span>مطب</span><span>دفتر وکالت</span><span>آموزشگاه رانندگی</span><span>صنعت و حرفه</span><span>نمایشگاه خودرو</span><span>سفر</span><span>مشاورهٔ مالیاتی</span><span>سالن</span><span>کافه</span><span>خرده‌فروشی</span><span>املاک</span><span>نظافت</span><span>مراقبت</span>",
    "audience.note": "مرجع ساختگی نداریم. نمونه‌های عمومی که سفارش واقعی نیستند با برچسب Konzeptprojekt مشخص می‌شوند.",
    "work.eyebrow": "روش کار",
    "work.title": "سه چیزی که پایبندش هستیم.",
    "work.1.t": "چندزبانه",
    "work.1.d": "آلمانی، انگلیسی، دری و فارسی. چیدمان واقعی راست‌به‌چپ، تایپ مناسب، تغییر زبانی که واقعاً سایت را اداره می‌کند.",
    "work.2.t": "از نظر فنی تمیز",
    "work.2.d": "موبایل‌محور، شفاف، بدون جلوه‌های اضافه. فایل‌ها را می‌گیرید — نه فقط یک ورود.",
    "work.3.t": "پشتیبانی شخصی",
    "work.3.d": "گفت‌وگو به زبان شما. اولین صحبت رایگان، پاسخ ظرف ۲۴ ساعت.",
    "honest.eyebrow": "شفاف",
    "honest.title": "بدون زندگی‌نامهٔ ساختگی.",
    "honest.body": "در این صفحه عکس تیم، رزومهٔ جعلی و نظر ساختگی نیست. مونیخ نقطهٔ اتکای ماست — نه تاریخچهٔ شرکتی ساختگی. اعتماد باید از کار روشن، بسته‌های قابل فهم و برچسب صادقانهٔ پروژه‌ها بیاید.",
    "close.title": "اول صحبت، بعد ساخت.",
    "close.lede": "چند جمله دربارهٔ کسب‌وکارتان، زبان مشتریان و هدف سایت کافی است. بدون تعهد.",
    "foot.home": "خانه",
    "foot.faq": "پرسش‌ها",
  },
};

export function getAboutCopy(lang) {
  return aboutCopy[lang] || aboutCopy.de;
}
